### ISSUE TITLE
ReleaseMgt plugin compatibility with Mantis 2.x

### ISSUE THREAD

**Issue by kjorsh** [mantisbt-plugins/releasemgt#7]
I am working on making plugin to work with Mantis 2.x. Is there any way to create a separate branch for this version so I can commit my changes?

**Comment by dregad** [comment]
@kjorsh are you interested in taking ownership of this plugin ? If so, I can grant you access to it.

Otherwise, just submit your PR against master branch. I don't see the need to create a separate one.

**Comment by kjorsh** [comment]
@dregad: Hello. I do not mind to take ownership as long it does not require too much time. Anyhow I want/need to make it work with Mantis 2.x to use myself. So, why not make it available for everyone... 
I have seen some plugins having two branches - 1.x and 2.x because of too big difference in plugin API. I though it may make sense to have it the same here.

**Comment by dregad** [comment]
> I do not mind to take ownership as long it does not require too much time. 

Considering that over the past 4 years there's been a whopping 4 issues, 3 pull requests and 16 commits since I migrated the plugin to Github, I wouldn't be too concerned about the workload...

Anyway, I would say that it should only take as much time as you'd be willing to invest :wink: 

> I have seen some plugins having two branches - 1.x and 2.x because of too big difference in plugin API

This was mainly because it was necessary to maintain support for Mantis 1.2, 1.3 and 2.x in parallel; in this specific case, I think it would be perfectly fine to just tag a release at the current HEAD, bump the version and minimum requirement and drop support for legacy MantisBT versions.

I'm not sure it would be worth the effort to release an intermediate version with for Mantis 1.3 (as requested in #6) since it is still officially supported. I let you decide if you want to do it or not.

**Comment by kjorsh** [comment]
2.x compatible version released
